import { chromium } from "playwright";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1100, height: 760 } });
await p.goto("http://localhost:18090", { waitUntil: "domcontentloaded" });
await p.waitForSelector('[data-testid="leaderboard"]', { timeout: 8000 });
await p.waitForTimeout(1500);
await p.screenshot({ path: "/tmp/fe-live-leaderboard.png", fullPage: true });
const bodyText = await p.locator('body').innerText();
console.log("shows E2E team:", bodyText.includes("E2E"));
console.log("shows DQ:", bodyText.includes("DQ"));
console.log("shows fixture 'Citadel':", bodyText.includes("Citadel"));
await b.close();
