import { chromium } from "playwright";
const errs = [];
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1150, height: 1000 } });
p.on("pageerror", (e) => errs.push("pageerror: " + e.message));
p.on("console", (m) => { if (m.type() === "error") errs.push("console: " + m.text()); });
await p.goto("http://localhost:18090", { waitUntil: "domcontentloaded" });
await p.waitForSelector('[data-testid="leaderboard"] tbody tr', { timeout: 10000 });
await p.locator('[data-testid="leaderboard"] tbody tr').first().click();
await p.waitForTimeout(3500);
await p.screenshot({ path: "/tmp/fe-detail.png", fullPage: true });
const hasDetail = await p.locator('[data-testid="run-detail"]').count();
const sessionCards = await p.locator('[data-testid^="session-"]').count();
const canvases = await p.locator('.uplot-host canvas').count();
console.log("run-detail rendered:", hasDetail, "| session cards:", sessionCards, "| chart canvases:", canvases);
console.log("errors:", errs.length); errs.slice(0,5).forEach(e=>console.log("  "+e));
await b.close();
