import { chromium } from "playwright";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1180, height: 1500 } });
await p.goto("http://localhost:18090", { waitUntil: "domcontentloaded" });
await p.locator('[data-testid="tab-live"]').click();
await p.waitForSelector('[data-testid="live-run-019e940b-9fd3-7ecd-83fc-fe1a90feac92"]', { timeout: 30000 }).catch(()=>{});
await p.waitForSelector('.live-session canvas', { timeout: 90000 });
await p.waitForTimeout(3000);
await p.screenshot({ path: "/tmp/fe-stacked.png", fullPage: true });
console.log("captured stacked live view");
await b.close();
