services:
  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:v0.15.0
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATA_SOURCE_NAME: postgres://iicpc:iicpc@postgres:5432/iicpc?sslmode=disable
    ports:
      - "9187:9187"

  loki:
    image: grafana/loki:main-2e3da9a
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    volumes:
      - loki_data:/loki

  prometheus:
    image: prom/prometheus:v2.54.1
    ports:
      - "9090:9090"
    volumes:
      - ./ops/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./ops/prometheus/iicpc-alerts.yml:/etc/prometheus/iicpc-alerts.yml:ro
      - prometheus_data:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:main-distroless-slim
    depends_on:
      - loki
      - prometheus
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_DEFAULT_THEME: system
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./ops/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./ops/grafana/dashboards:/var/lib/grafana/dashboards:ro

volumes:
  grafana_data:
  loki_data:
  prometheus_data:
