#!/usr/bin/env bash
# Local k3s bring-up of the whole IICPC platform — clone-and-go.
#
# Platform images are PULLED from the public GHCR namespace ghcr.io/agrawalx/*:demo
# (no local docker build/import needed — only k3s + kubectl). Contestant images are
# still built in-cluster by the spawner (kaniko) and pushed to the in-cluster
# registry, so a fresh clone needs no local docker at all.
#
# Trims vs the committed (EKS) manifests: Kafka 1 broker RF=1, all replicas 1,
# gVisor off (runc), NetworkPolicies skipped, in-cluster registry for contestant
# images. Seeds the FULL 50k/s constant scenario (override the *_RPS env below for
# a weaker machine). None of this touches the committed manifests.
#
# Prereqs: a running k3s (or any single-node k8s) + kubectl context pointing at it.
# Then:  deploy-local/up.sh  ->  deploy-local/forward.sh  ->  open http://localhost:8080
set -euo pipefail
cd "$(dirname "$0")/.."
K="kubectl"

NODE_IP="$(${K} get nodes -o jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}')"
REG="${NODE_IP}:5000"
echo ">> node IP ${NODE_IP}; registry ${REG}"

# ---- in-cluster registry trust (contestant images) -----------------------
# Contestant submissions are built in-cluster (spawner/kaniko) and pushed to the
# in-cluster registry at ${REG}. The k3s node must be told to pull from it over
# plain HTTP, via /etc/rancher/k3s/registries.yaml. That path + a k3s restart are
# ROOT, so up.sh only GENERATES the file (from THIS node's IP) and checks it's
# installed — it warns instead of silently letting submission pulls fail later.
REGISTRIES_YAML="deploy-local/registries.yaml"
cat > "$REGISTRIES_YAML" <<EOF
# Generated by up.sh for node ${NODE_IP}. Install (root), then restart k3s:
#   sudo cp ${REGISTRIES_YAML} /etc/rancher/k3s/registries.yaml && sudo systemctl restart k3s
mirrors:
  "${REG}":
    endpoint:
      - "http://${REG}"
configs:
  "${REG}":
    tls:
      insecure_skip_verify: true
EOF
if ! grep -q "\"${REG}\"" /etc/rancher/k3s/registries.yaml 2>/dev/null; then
  echo "!! /etc/rancher/k3s/registries.yaml is missing the ${REG} mirror."
  echo "!! Contestant builds will fail to pull until you run (ROOT), then re-run up.sh:"
  echo "!!   sudo cp ${REGISTRIES_YAML} /etc/rancher/k3s/registries.yaml && sudo systemctl restart k3s"
fi

# ---- dev credentials (local only) ----------------------------------------
PG_PW=devpass ; TS_PW=devpass
MINIO_AK=minioadmin ; MINIO_SK=minioadmin123
DB="postgres://iicpc:${PG_PW}@postgres.data.svc.cluster.local:5432/iicpc?sslmode=disable"
TSDB="postgres://iicpc:${TS_PW}@timescaledb.data.svc.cluster.local:5432/metrics?sslmode=disable"
KB="kafka.data.svc.cluster.local:9092"
REDIS_ADDR="redis.data.svc.cluster.local:6379"
REDIS_URL="redis://redis.data.svc.cluster.local:6379"

mk() { ${K} create secret generic "$1" -n "$2" "${@:3}" --dry-run=client -o yaml | ${K} apply -f - ; }
applynp() { find "$1" -name '*.yaml' ! -name '*network-policy*' ! -name 'namespace.yaml' ! -name '*.ecr.yaml' -print0 | xargs -0 -I{} ${K} apply -f {} ; }

echo "== 1. namespaces =="
for ns in data build platform sandbox benchmark observability; do ${K} apply -f k8s/$ns/namespace.yaml; done

echo "== 2. secrets =="
mk postgres-secret data --from-literal=password=$PG_PW
mk timescaledb-secret data --from-literal=password=$TS_PW
mk minio-secret data --from-literal=access-key=$MINIO_AK --from-literal=secret-key=$MINIO_SK
KID=$(python3 -c "import uuid,base64;print(base64.urlsafe_b64encode(uuid.uuid4().bytes+uuid.uuid4().bytes[:4]).decode().rstrip('='))")
mk kafka-secret data --from-literal=cluster-id=$KID
mk submission-api-secret platform --from-literal=database-url="$DB" --from-literal=minio-access-key=$MINIO_AK --from-literal=minio-secret-key=$MINIO_SK
${K} apply -f bootstrap/secrets-live/platform-auth-api.yaml
mk leaderboard-api-secret platform --from-literal=database-url="$DB" --from-literal=timescale-url="$TSDB" --from-literal=kafka-brokers="$KB" --from-literal=redis-addr="$REDIS_ADDR"
mk spawner-secret build --from-literal=database-url="$DB" --from-literal=minio-access-key=$MINIO_AK --from-literal=minio-secret-key=$MINIO_SK --from-literal=harbor-staging-endpoint="$REG" --from-literal=harbor-production-endpoint="$REG" --from-literal=harbor-user=anon --from-literal=harbor-password=anon
mk bot-fleet-controller-secret benchmark --from-literal=database-url="$DB"
mk correctness-validator-secret benchmark --from-literal=kafka-brokers="$KB" --from-literal=database-url="$DB"
mk score-computer-secret benchmark --from-literal=database-url="$DB" --from-literal=timescale-url="$TSDB" --from-literal=kafka-brokers="$KB" --from-literal=redis-addr="$REDIS_ADDR"
mk telemetry-ingester-secrets benchmark --from-literal=KAFKA_BROKERS="$KB" --from-literal=TIMESCALE_URL="$TSDB" --from-literal=REDIS_URL="$REDIS_URL"
mk grafana-admin observability --from-literal=admin-user=admin --from-literal=admin-password=admin

echo "== 3. registry =="
${K} apply -f deploy-local/registry.yaml

echo "== 4. data tier (kafka patched to 1 broker / RF=1) =="
${K} apply -f k8s/data/postgres/service.yaml -f k8s/data/postgres/statefulset.yaml
${K} apply -f k8s/data/timescaledb/service.yaml -f k8s/data/timescaledb/statefulset.yaml
${K} apply -f k8s/data/minio/service.yaml -f k8s/data/minio/statefulset.yaml
${K} apply -f k8s/data/redis/service.yaml -f k8s/data/redis/statefulset.yaml
${K} apply -f k8s/data/kafka/service.yaml
# single-broker kafka: replicas 1, single quorum voter, RF/ISR=1
sed -e 's/replicas: 3/replicas: 1/' \
    -e 's#0@kafka-0.kafka.data.svc.cluster.local:9093,1@kafka-1.kafka.data.svc.cluster.local:9093,2@kafka-2.kafka.data.svc.cluster.local:9093#0@kafka-0.kafka.data.svc.cluster.local:9093#' \
    -e 's/value: "3"/value: "1"/g' -e 's/value: "2"/value: "1"/g' \
    k8s/data/kafka/statefulset.yaml | ${K} apply -f -

echo ">> waiting for data tier..."
${K} -n data rollout status statefulset/postgres --timeout=180s
${K} -n data rollout status statefulset/timescaledb --timeout=180s
${K} -n data rollout status statefulset/kafka --timeout=180s
${K} -n data rollout status statefulset/minio --timeout=120s || true
${K} -n data rollout status statefulset/redis --timeout=120s || true

echo "== 5. kafka topics (RF=1) =="
sed -e 's/--replication-factor 3/--replication-factor 1/' \
    -e 's/min.insync.replicas=2/min.insync.replicas=1/' \
    k8s/data/kafka/topic-init-job.yaml | ${K} apply -f -
${K} -n data wait --for=condition=complete job/kafka-topic-init --timeout=180s || ${K} -n data logs job/kafka-topic-init | tail

echo "== 6. observability =="
applynp k8s/observability
# add TimescaleDB datasource so latency (metrics.p99_ns/tps) is queryable in Grafana
${K} apply -f deploy-local/grafana-timescale-datasource.yaml
${K} -n observability rollout restart deployment/grafana 2>/dev/null || true

echo "== 7. build (rbac + spawner) =="
${K} apply -f k8s/build/rbac.yaml
applynp k8s/build/spawner
${K} -n build set env deployment/spawner \
  HARBOR_PROJECT=iicpc REGISTRY_INSECURE=true \
  HARBOR_STAGING_ENDPOINT="$REG" HARBOR_PRODUCTION_ENDPOINT="$REG"

echo "== 8. platform (submission-api, auth off, full 50k seed, leaderboard) =="
applynp k8s/platform/submission-api
# AUTH off: the visitor is always DEFAULT_CONTESTANT_ID. It MUST match the frontend's
# NEXT_PUBLIC_DEFAULT_CONTESTANT_ID (baked default: echo-contestant) so a submission
# made in the UI is owned by, and re-readable/benchmarkable by, the same identity.
# RESEED_SCENARIOS=true rebuilds scenarios from the *_RPS/_DURATION env on every boot
# (constant 50k = 50 HFT tasks x1000 rps). Lower CONSTANT_TOTAL_RPS for a weak box.
${K} -n platform set env deployment/submission-api \
  AUTH_REQUIRED=false DEFAULT_CONTESTANT_ID=echo-contestant RESEED_SCENARIOS=true \
  SEED_SCENARIOS=constant \
  CONSTANT_TOTAL_RPS=25000 SPIKE_PEAK_RPS=50000 RAMP_PEAK_RPS=50000 \
  CONSTANT_DURATION_S=60 SPIKE_DURATION_S=60 RAMP_DURATION_S=180
applynp k8s/platform/leaderboard-api
[ -d k8s/platform/auth-api ] && applynp k8s/platform/auth-api || true
applynp k8s/platform/frontend || true

echo "== 9. sandbox orchestrator (runc, capture on) =="
${K} apply -f k8s/sandbox/sandbox-orchestrator/rbac.yaml
applynp k8s/sandbox/sandbox-orchestrator
${K} -n sandbox set env deployment/sandbox-orchestrator \
  RUNTIME_CLASS- SANDBOX_NODE_POOL- ALGO_CPU=1 \
  CAPTURE_ENABLED=true CAPTURE_IMAGE=ghcr.io/agrawalx/ebpf-latency:demo

echo "== 10. benchmark tier =="
applynp k8s/benchmark/telemetry-ingester
applynp k8s/benchmark/correctness-validator
applynp k8s/benchmark/score-computer
${K} apply -f k8s/benchmark/bot-fleet-controller/deployment.yaml
${K} -n benchmark set env deployment/bot-fleet-controller \
  SANDBOX_ORCHESTRATOR_URL=http://sandbox-orchestrator.sandbox.svc.cluster.local:8080
applynp k8s/benchmark/bot-fleet
${K} -n benchmark scale deployment/bot-fleet --replicas=1

echo "== 11. trim platform replicas to 1 (laptop) =="
${K} -n platform scale deployment/submission-api deployment/leaderboard-api --replicas=1 2>/dev/null || true
${K} -n platform scale deployment/auth-api deployment/frontend --replicas=1 2>/dev/null || true

echo ">> waiting for core services..."
for d in platform/submission-api platform/leaderboard-api benchmark/telemetry-ingester benchmark/correctness-validator benchmark/score-computer benchmark/bot-fleet-controller sandbox/sandbox-orchestrator build/spawner; do
  ns=${d%/*}; name=${d#*/}
  ${K} -n $ns rollout status deployment/$name --timeout=120s || echo "WARN: $d not ready"
done
echo
echo "=== UP. Run deploy-local/forward.sh, then open http://localhost:8080 and submit your zip in the UI ==="
